### ISSUE TITLE
Permission denied when trying to set up externals on single file inside existing folder

### ISSUE THREAD

**Issue by francescopitzalis** [develersrl/git-externals#44]
Let's say I have a repository Repo1 with this structure:
```
Repo1
  src
    classes
      A.cls
```
and another repository Repo2:
```
Repo2
  src
    classes
      B.cls
      C.cls
```
And I want to set up an externals on B.cls in order to have it (and just that class) available in Repo1 at the same directory level:
```
Repo1
  src
    classes
      A.cls
      B.cls -> Repo2/src/classes/B.cls
```

From the documentation I understood it was
```
git externals add --branch=master git@github.com:username/Repo2.git /src/classes/B.cls /src/classes/B.cls
```
Resulting in
```
{
    "git@github.com:username/Repo2.git": {
        "branch": "master",
        "ref": null,
        "targets": {
            "/src/classes/B.cls": [
                "/src/classes/B.cls"
            ]
        },
        "vcs": "git"
    }
}
```
But running `git externals update` results in
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/git-externals", line 9, in <module>
    load_entry_point('git-externals==0.5.0', 'console_scripts', 'git-externals')()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/git_externals/cli.py", line 121, in gitext_update
    gitext_up(recursive, reset=reset, use_gitsvn=gitsvn)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/git_externals/git_externals.py", line 401, in gitext_up
    link_entries(git_externals)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/git_externals/git_externals.py", line 230, in link_entries
    link(os.path.abspath(src), dst)
OSError: [Errno 13] Permission denied
```

Am I doing something wrong or this is actually a bug?
Or maybe `git externals` support single files only at repository root level?

**Comment by naufraghi** [comment]
> Or maybe git externals support single files only at repository root level?

It should work, but the single file feature is not used in the projects I'm aware, you may have found a bug.

Can you modify you local `git_externals.py` to print out `os.path.abspath(src)` and `dst`?

**Comment by francescopitzalis** [comment]
I did it and I found out it was my bad. This is NOT a bug and this issue can be closed.

Here the explanation in case someone else makes my stupid mistake.

The command
```
git externals add --branch=master git@github.com:username/Repo2.git /src/classes/B.cls /src/classes/B.cls
```
is wrong, because I used the leading '/', resulting in the script attempting to make a symlink at root level.

The correct version of that command is
```
git externals add --branch=master git@github.com:username/Repo2.git src/classes/B.cls src/classes/B.cls
```

which produces the correct git_externals.json:
```
{
    "git@github.com:username/Repo2.git": {
        "branch": "master",
        "ref": null,
        "targets": {
            "src/classes/B.cls": [
                "src/classes/B.cls"
            ]
        },
        "vcs": "git"
    }
}
```

and running `git externals update` works like a charm.
